run:
	export DATABASE_URL=postgres://jozwiaka:password@localhost:5433/collaboration_novel_platform_db && \
	cargo run > output.log 2>&1
	# cargo sqlx prepare && \
	# cargo build --release && \
	#  ./target/release/authentication_service 